# Generated by Django 4.1.6 on 2023-04-28 12:29

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100, unique=True)),
                ('Email', models.CharField(blank='', max_length=50, unique=True)),
                ('MobileNumber', models.CharField(default='', max_length=15)),
                ('Address', models.CharField(blank='', max_length=100)),
                ('City', models.CharField(default='', max_length=100)),
                ('State', models.CharField(default='', max_length=100)),
                ('Credits', models.IntegerField(default=0)),
                ('Password', models.CharField(default=app.models.password, max_length=15)),
                ('otp', models.CharField(default=app.models.otp, max_length=10)),
                ('Role', models.CharField(default='Admin', max_length=100)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('tags', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Features', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('Email', models.CharField(blank='', max_length=50, unique=True)),
                ('MobileNumber', models.CharField(default='', max_length=15)),
                ('Address', models.CharField(blank='', max_length=100)),
                ('City', models.CharField(default='', max_length=100)),
                ('State', models.CharField(default='', max_length=100)),
                ('Credits', models.IntegerField(default=0)),
                ('Password', models.CharField(default=app.models.password, max_length=15)),
                ('otp', models.CharField(default=app.models.otp, max_length=10)),
                ('Role', models.CharField(default='user', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 4, 28, 17, 59, 24, 709128))),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=500)),
                ('option1', models.CharField(default='', max_length=200)),
                ('option2', models.CharField(default='', max_length=200)),
                ('option3', models.CharField(default='', max_length=200)),
                ('option4', models.CharField(default='', max_length=200)),
                ('answer', models.CharField(default='', max_length=200)),
                ('Assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Question_list', to='app.assessment')),
            ],
        ),
    ]
