# Generated by Django 4.1.6 on 2023-04-28 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_recruiters_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 18, 6, 51, 212855)),
        ),
    ]
