# Generated by Django 4.1.6 on 2023-04-28 12:39

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_recruiters_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='name',
            field=models.CharField(default=app.models.name, max_length=50),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 18, 9, 20, 447957)),
        ),
    ]
