# Generated by Django 4.1.6 on 2023-05-04 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_assessment_url_alter_recruiters_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiters',
            name='primary_colour',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='recruiters',
            name='secondary_colour',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_colour',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_colour',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 18, 18, 35, 49943)),
        ),
    ]
