# Generated by Django 4.1.6 on 2023-05-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_recruiters_master_primary_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 13, 14, 28, 404187)),
        ),
    ]
